# Generated by Django 5.2.1 on 2025-05-24 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpost',
            old_name='categories',
            new_name='category',
        ),
    ]
