# Generated by Django 5.2.1 on 2025-06-23 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_blogdetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogdetail',
            name='post',
            field=models.ManyToManyField(related_name='post_detail', to='blog.blogpost'),
        ),
    ]
