# Generated by Django 5.2.1 on 2025-07-11 06:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_blogdetail_post'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogpost',
            options={'verbose_name_plural': 'blog_posts'},
        ),
        migrations.AddField(
            model_name='blogpost',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='pdf_files/'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='blog.blogpost'),
        ),
        migrations.DeleteModel(
            name='BlogDetail',
        ),
    ]
